### ISSUE TITLE
Documentation: View Source of SCSS pages broken

### ISSUE THREAD

**Issue by xanderwebs** [thumbtack/thumbprint#120]
To replicate:

Go to any component that has a SCSS version > Click `View source`

Expected: Land in github page

Actual: 404

(I've confirmed these steps for a number of pages: Avatar, Alert, Block List, Button etc).

**Comment by danoc** [comment]
Thanks, Alex! Should be a quick fix.

**Comment by danoc** [comment]
Some more background: it's 404'ing because we've [moved all of our SCSS packages](https://github.com/thumbtack/thumbprint/issues/38) into a `thumbprint-scss` package (similar to what we did with React).

We haven't deployed that version of the docs yet since website needs to be migrated. @tomgenoni and I will be doing that on Monday. After that, we'll deploy the new docs and the links won't 404.

**Comment by xanderwebs** [comment]
Got it. I figured it was something like that, but when I glanced at the repo I couldn't quite figure out where to make that change, so I filed the issue. ✌️

**Comment by danoc** [comment]
@xanderwebs — I've fixed the 404's so I'll close this.

There's a related task (#120) that I'll keep open.

**Comment by xanderwebs** [comment]
Is #120 the right link to the related task?

**Comment by danoc** [comment]
Whoops. Meant #102.
