### ISSUE TITLE
Should the back button close open modals?

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#136]
If so, how would that work? Should it be part built-into the component? Or do consumers set that up?

(Thumbtack employees can refer to FE-1589 for previous context.)

**Comment by hsiaoman87** [comment]
Specifically this is the expected behavior on mobile devices

**Comment by lavelle** [comment]
Trying to clarify expected behaviour here. Here's what I have so far

1. User can specify a custom hash for their modal, for example `#comments`
2. When the modal is opened, this hash is added to the URL
3. When the modal is closed (by any method) this hash is removed from this URL
    a. Close button
    b. Browser back button
    c. ESC key
4. Pressing back while the modal is open closes the modal (and removes the hash, see 3)
5. Pressing forward again when the modal has been previously opened and closed will open it again (but if it has never been opened, it will do nothing).
6. Pressing back while the modal is closed returns to the previous page
7. Pasting the URL with the hash (eg. `#comments`) causes the modal to open itself when the page loads. If the hash is not present the page loads with the modal closed.

**Comment by lavelle** [comment]
Here's a [simple demo ](https://codesandbox.io/s/modal-mobile-demo-y0772)that supports most of the core assumptions. Back, forward, and updating the URL all work as expected. The only thing missing is #7 (opening the URL with the hash already present does not cause the modal to appear. But this could be easily added with a `componentDidMount` check.

You will need to preview the demo [here](https://y0772.codesandbox.io/) rather than inside codesandbox preview window, to get the real browser button behaviour.

Dan and I have chatted and after outlining the assumptions above, we are leaning towards recommending that people who want this behaviour implement it as shown in that demo in their parent component, and we will close the issue for now.

If this same problem comes up multiple times, and there are many places in website that need this behaviour, we can look into extracting out the functionality into a shared component or utility that wraps the default modal. We can also raise this in the FE committee if you think it warrants further discussion.
