### ISSUE TITLE
Modify DatePicker to support month/year pickers

### ISSUE THREAD

**Issue by zboman** [thumbtack/thumbprint#193]
The current version of `DatePicker` is great if you're only selecting a date that is close to today (or another reference date). But because the default behavior of `react-day-picker` doesn't allow the user to change the month or year directly, it is very difficult to pick a date that is a long time from now. 

*Use case:* We're building a date picker to select the user's date of birth. Even if we initialize `DatePicker` to some date in the past (like Jan 1, 1980 or something), if the user is 50 years old, that's still a lot of months to click through. Our current solution is to use `<input type="date">` but that isn't supported by IE11/Safari and we'd like a cross-browser, company-supported solution.

My proposal would be to add a month select and a year select to the picker, similar to [this `react-day-picker` example](http://react-day-picker.js.org/examples/elements-year-navigation/). Obviously we'd want to style the `select` elements better than is done in the example, but the basic functionality would be the same. 

In the process, I would also resolve #150.

**Comment by benknight** [comment]
Designers might want to weight in on this but I would say the use cases for using a calendar UI to select a date are mostly aimed at selecting dates that are in the near future or recent past.  Once you get more than a year or so back or more, the day of the week becomes less important and it's more intuitive to specify a date directly as a combination of year/month/day.

I vote we leave DatePicker as is, and for use cases like birthdates either use an open <input type=text>  or, if necessary, a grouping of <select>.

Here's Facebook's signup page for example:

<img width="453" alt="Screen Shot 2019-04-02 at 9 04 58 PM" src="https://user-images.githubusercontent.com/786691/55408868-1acd7b80-558b-11e9-8fd9-ad853bb44b1a.png">

**Comment by benknight** [comment]
From https://www.nngroup.com/articles/date-input:

> Calendar pickers should be used for events close to the present time — within less than a year.

> Typing the date is the most basic option for date input, yet in many cases it is the most efficient one, especially when the date is further away in the past (e.g., birthdate) or future. We recommend that you allow users to type the date even if other input methods are available.

**Comment by danoc** [comment]
Thanks for the issue, @zboman!

Great points. I agree with @benknight here that `DatePicker` may not be the best UI. @tomgenoni, what do you think?

**Comment by tomgenoni** [comment]
I also agree with @benknight here. 

My usual default is to go with `<select>`s. They aren't ideal given the relatively high number of options but I think they are preferable to  `<input>`s because there's no possible confusion about the format (e.g, "is the month `07` or `7`?") and the choices are predictable. 

This proposes a hybrid that uses an input for the year to cut down the length of the year input https://designnotes.blog.gov.uk/2013/12/05/asking-for-a-date-of-birth/

And, of course, here's another variation editing your birthday in your Google account.
![Uploading Screen Shot 2019-04-02 at 4.34.34 PM.png…]()

**Comment by benknight** [comment]
Yeah I think basically it comes down to two options when it comes to a far-off date like a birthday: `<select>` or `<input>`.   As @tomgenoni noted, `<select>` is better when a specific format is necessary, but I agree with the NNGroup article that an open text field provides the least amount of friction for the user.

Based on what I know about the project, my assumptions are that the form Zack is building goes into a queue in Salesforce that will be manually processed by admins.  Given this is the case, an open text field seems sufficient to me so that's my official recommendation.

I would also specifically note that `<input type=date>` here is also to be avoided.  Mostly because in basically every implementation it provides a calendar UI to the user.  In some cases a date can be manually typed in, but at least in the case of Chrome for Android, this was not possible, and using the calendar to select a past date was awkward and something not all users would be able to figure out (you have to tap on "2019" to bring up a year selection).

It seems to me that given the inconsistent implementations of `<input type=date>` we should make it an official guidelines specifically not to use it.  @tomgenoni do you think that's a good idea?

**Comment by danoc** [comment]
> It seems to me that given the inconsistent implementations of `<input type=date>` we should make it an official guidelines specifically not to use it. @tomgenoni do you think that's a good idea?

We don't support `type="date"` in our `Input` component for that reason. I'd be happy to accept a PR that expands on the documentation for the `type` prop to include that point.

**Comment by tomgenoni** [comment]
> Based on what I know about the project, my assumptions are that the form Zack is building goes into a queue in Salesforce that will be manually processed by admins. Given this is the case, an open text field seems sufficient to me so that's my recommendation for his use case.

For that use case I agree text `<input`> are the way to go. But I do think it depends on the audience we expect to interact with it and how often (e.g., the one-time Facebook sign-up vs repetitive manual entries). Not sure we need guidelines at this point but I'm not ready to endorse `<input>` as our official way of handling date of birth entires. 

> It seems to me that given the inconsistent implementations of <input type=date> we should make it an official guidelines specifically not to use it. @tomgenoni do you think that's a good idea?

Yup, added #202 to track this.

**Comment by danoc** [comment]
Hi! Going to close this since it seems that modifying the DatePicker isn't the best solution in this case.
