### ISSUE TITLE
DatePicker dot positioning broken at around 350px ~ 500px in Thumbprint Docs

### ISSUE THREAD

**Issue by senseiurata** [thumbtack/thumbprint#244]
Some issues with the dot that could be better:
- Not truly centered - it is positioned by hard px values, even though the grids can shrink. Right now there's a hacky media query (350px max-width) to compensate for the shrinking grid.
- The '·' character is used at 48px to draw the circle - we could use a CSS circle instead.
- There are some px and rem are mixed in the file, which means there could be inconsistencies based on browser settings.

https://cl.ly/3a254b01ea97

**Comment by danoc** [comment]
Thanks for filing!

@komatsu — Would you be able to take a look at this?

**Comment by komatsu** [comment]
Few things here:
1. We can't use a css circle here since the dot with a `::after` pseudo-class, unless we want to fork the underlying `react-day-picker` and build this logic in to that component.
2. Using px positioning for this dot is still correct since the cell widths themselves are defined in px. The cell styling needs to be changed to rem's first before anything with the dot positioning changes.
3. It looks like the problem is resulting from the Thumbprint doc page's layout rather than the component. If you take this DatePicker and place it in a page that doesn't have a bounding container (or 100% width), then the positioning of the dots work correctly. What we're seeing in the Thumbprint docs page is that shrinking the page is prematurely shrinking the width of each DatePickerDayCell before the 350px breakpoint is hit, thereby messing with the positioning. You'll notice that the positioning of the pagination buttons are broken as well in this scenario. The styles that are unrelated to this dot positioning have to be altered first so that they depend on the parent container width and not the page widths.

Unfortunately, I don't have the cycles to tackle all of these at the moment. @danoc @senseiurata

**Comment by senseiurata** [comment]
I can take a look - after filing this issue I may have managed to get CSS circle to work (with just ::after) by adjusting the CSS in-browser, but would like to test on other browsers

**Comment by danoc** [comment]
This has been fixed. Thanks @senseiurata!
