### ISSUE TITLE
Documentation: View Source on React components takes you to general dir, not specific source

### ISSUE THREAD

**Issue by bawjensen** [thumbtack/thumbprint#547]
E.g. from https://thumbprint.design/components/button/react/ I click "View source" and get directed to https://github.com/thumbtack/thumbprint/tree/master/packages/thumbprint-react.

Perhaps this is the intended effect, or a solution is complicated... Regardless it just didn't seem quite right to me. Not a big issue by any means.

**Comment by danoc** [comment]
Hey @bawjensen, thanks for the issue. I agree that this is confusing. 

We first added the package table to the top of the component pages when each component was its own NPM package. Back then it was easy to link to the source because each component had the `source` defined in its `package.json`. Today all of the components are in one of two packages: `thumbprint-react` or `thumbprint-scss` package. The consolidation means that the previous approach doesn't work as well.

One way to fix this is by adding the proper URL in the `*.mdx` file front-matter for each component. The downside is this increases the complexity/maintenance cost. Also, the nearby "Changelog" and "Report issue" links would continue to have the same problem of not being specific to a component.

I'm going to close this one as a "won't fix" because I don't think that the benefits of linking to the exact file outweigh the cost of the proper solution. In the future, we may want to consider re-desinging the table at the top of the pages to indicate all of the information, outside of the import statement, are about the NPM package, not the component itself.

cc: @volanStudio, @tomgenoni
