### ISSUE TITLE
Calendar component is missing props in the documentation

### ISSUE THREAD

**Issue by danoc** [thumbtack/thumbprint#586]
I'm only seeing these three props.

![image](https://user-images.githubusercontent.com/916038/70655741-a238b780-1c0d-11ea-8ada-6b9d6b8ded45.png)

**Comment by volanStudio** [comment]
Calendar has its `PropTypes` in a separate `types.d.ts` file unlike the rest of our components. Moving them into the component as an interface fixes the issue. My reservation about pushing this solution is that I'm a ts n00b.

If we move them into the `index.ts` it picks them up just fine but ts chokes on the `Modifier` type that it uses for the `disabledDays` prop. Replacing `Modifier` with `any` solves it, but I bet there is a better solution that someone with more ts knowledge would spot instantly.

**Comment by danoc** [comment]
Thanks for digging into it! In which way does it choke on `Modifier`?

**Comment by volanStudio** [comment]
`Modifer` isn't a defined type, but it turns out we can define it - Typescript is kinda awesome!

I just dug into `index signatures` in the typescript docs. It turns out that we can define the `Modifier` type in the types file and move the interface for our `PropTypes` into the index so we get the benefit of having the props in the docs.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1928396/72266754-01169580-35ed-11ea-892b-aad95b903a97.png">
