### ISSUE TITLE
Omitting `value` prop in `<Dropdown />` doesn't cause any runtime console warnings or errors

### ISSUE THREAD

**Issue by bawjensen** [thumbtack/thumbprint#652]
My best guess is that this is related to the migration to typescript. In the source the `PropTypes` interface does properly define `value: string;`, notably non-optional, which is reflected in the docs marking this as required:
![image](https://user-images.githubusercontent.com/5619111/76349079-8f925500-62c6-11ea-9e24-6181669ecc1e.png)

However at runtime there doesn't seem to be any console error/warning. Given I believe that functionality was provided by the `prop-types` npm module, perhaps switching to typescript means it's not possible that have that anymore? Hard to say without knowing the specifics of how the typescript code is transformed in the build step.

**Comment by danoc** [comment]
Hi!

> However at runtime there doesn't seem to be any console error/warning. Given I believe that functionality was provided by the `prop-types` npm module, perhaps switching to typescript means it's not possible that have that anymore?

That's right. It wouldn't show up in the console anymore. BUT, ideally you'd get this information in your code editor because TypeScript knows that the prop is required. @lavelle, do you know why this might not be working?

**Comment by bawjensen** [comment]
> [...] BUT, ideally you'd get this information in your code editor because TypeScript knows that the prop is required. @lavelle, do you know why this might not be working?

Would that apply when my source code is JSX not TSX? I'm thinking of `website` code, in this instance

**Comment by lavelle** [comment]
Yeah, that's an interesting one. In website we don't run typechecking on JS(X) files because they will have hundreds of their own type errors and we haven't done that burndown list yet.

It would be nice if TypeScript had an option for "typecheck JS files, but only in the places where they call code from TS files". We would be able to enable such an option easily, but unfortunately there's no such option.

We should probably prioritise enabling JS typechecking in website with a whitelist for all existing errors, so people consuming TP React components get type warnings, so matter what type of code they're writing.

**Comment by danoc** [comment]
Another option is to support both PropTypes and TypeScript in the transition phase. (But it'd be a lot of work at this point since we've removed the PropTypes as we've converted files over.)

**Comment by lavelle** [comment]
Yeah, I'd personally prefer not to do that, it's a lot of duplication and extra boilerplate. I will add the checkJs whitelist to our TypeScript infra doc and try and prioritise that.

If there is a prop like this where it's really urgent to get a runtime error in the meantime, we could always log something with the `warning` package directly.

**Comment by bawjensen** [comment]
I’m also not super keen on having propTypes alongside the interface. I’m not sure I follow what you’re describing, though, Giles. How is it even possible to statically check JSX given it doesn’t have types?

**Comment by lavelle** [comment]
TypeScript can do some limited typechecking on JS files using the information available to it. This includes JSDoc types, the types of methods in the standard library (eg. it knows that `Math.random()` returns a `number`) and the types of constants `eg. it knows that `const x = 'hello';` is a `string`.

As you'd imagine, if we enable the `checkJs` option to check our JS(X) files, we get hundreds of these errors. So the best plan is to enable it, whitelist all erroring files, and burn down the list. Then you would be able to remove the file you're working on from that list, and you'd get type errors in it. This would tell you that you're not passing a `value` to `Dropdown`. It would also give you a bunch of other errors, so it'd be your responsibility to fix all of those two as part of your CR.

Further reading: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by bawjensen** [comment]
ah cool, it may be an imperfect solution but that does sound pretty awesome. And that'd address my case, as you mention

**Comment by lavelle** [comment]
So I dug into this a bit today and it's a bit tricker than it initially seems.

The only method TypeScript has for whitelisting files is the `excludes` key in the `tsconfig.json` file. There's no such thing as a `.tsignore` file. Unfortunately, this `excludes` key only excludes _entry points_, not files that are imported by another file. So you can exclude `b.js`, but if `a.js` imports `b.js`, it will get typechecked and its errors will be reported anyway.

This means that to burn down a single file and get it passing the typechecker, you have to fix every error in every file in the dependency tree that involves that file.

There is also the issue that most people at the company are not familiar with TypeScript yet. If we went with a whitelist approach, and required that all new JS files pass the typechecker, lots of people would probably be confused by the errors they were getting.

These two things lead me to believe that a burndown list for typechecking JS files is both technically infeasible, and probably not desirable.

Instead, we probably want to have an opt-in system, where someone who wants to get typechecking in their JS files explicitly adds it to the `includes` property in `tsconfig.json`. They would then be responsible for fixing all type errors in all files in their file's dependency tree before merging.

However, if someone is going to all of that trouble, it almost feels like they should take the time to just convert the component to TS. It seems weird to spend a lot of effort getting a JS file to pass the TS typechecker, but not go all the way and convert it to TS and get full typechecking. This leads me right back to the start and wondering if we should enable JS checking at all, or just require anyone who wants typechecking in their file to convert their file to TS first.

This ironically _would_ fix the "a imports b" issue, because while `checkJs` is `false,` no JS files are typechecked, even if they are imported by TS files that are typechecked. That means you could selectively convert your single file to TS and fix any type errors in that one file, without having to fix everything in the dependency tree. This would probably be more appealing to most people, and has the advantage that the file that gets converted is then fully typechecked, rather than just half-typechecked.

Would be interested to know what you guys think about this.

**Comment by lavelle** [comment]
Closing here since we've moved this to company Slack. Seems like more of a website-tooling question, than a question for this library now.
